name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-docker-image:
    name: Build hdsentinel-mqtt image and push to docker.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
        with:
          flavor: latest=true
          images: |
            gszoboszlai/hdsentinel-mqtt-ha
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}} 

      # Ensure Docker Buildx is set up
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
        with:
          install: true

      # Login to Docker registry
      - name: Log into Docker registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: docker.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Optional: Verify built image
      - name: Verify Docker image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          docker pull $TAG
          docker inspect $TAG
