name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-docker-image:
    name: Build hdsentinel-mqtt image and push to docker.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=true
          images: |
            gszoboszlai/hdsentinel-mqtt-ha
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}} 

      # Ensure Docker Buildx is set up
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      # Login to Docker registry
      - name: Log into Docker registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Optional: Verify built image
      - name: Verify Docker image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker pull ${{ steps.meta.outputs.tags[0] }}
          docker inspect ${{ steps.meta.outputs.tags[0] }}
